[versions]
# Versões que o Claudio definiu
kotlin = "2.1.0"
agp = "8.7.0"
composeBom = "2025.01.00"
hilt = "2.57.2" # <--- ATUALIZADO PARA 2.57.2
room = "2.6.1"
ksp = "2.1.0-1.0.29"

[libraries]
# Referências para os imports funcionarem
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

[plugins]
# O SEGREDO DO KOTLIN 2.1.0 ESTÁ AQUI:
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
